Fix latex embedded lexer
pygments/pygments pull request #1517
Opened 2020-08-20 22:57 UTC by eric-wieser

Closes gh-1516

2020-08-20 22:58 UTC, eric-wieser commented on pygments/formatters/latex.py
> -                    index += len(a)
This line was a bug, it should have been outside the `for` loop

2020-08-20 22:58 UTC, eric-wieser commented on pygments/formatters/latex.py
> -                for i, t, v in self.lang.get_tokens_unprocessed(a):
This wasn't safe - the nested tokenizer needs to see all the text at once, not just be served chunks of it at a time

2020-09-12 15:17 UTC, Anteru requested changes
Thanks! We have some merge conflicts due to the latest `yield from` improvements -- could you please take a look and update this as needed?

2020-09-14 17:28 UTC, eric-wieser commented
Conflicts resolved, the changes in #1537 were irrelevant

2020-09-27 06:06 UTC, Anteru commented
I did look at this and it all seems fine, but I don't quite understand the original code. Please bear with me -- I just need to convince myself it works (I'm fairly certain it does no harm :) ).

2020-09-29 20:59 UTC, eric-wieser commented
I wouldn't spend too much time understanding the old code - it had both indentation mistakes and a bad design...

2020-09-30 07:41 UTC, merged

2020-09-30 07:42 UTC, Anteru commented
Fair enough -- it does have tests now so I doubt it can be any worse than the original one; sorry for taking that long to merge.