add WebAssembly lexer
pygments/pygments pull request #1564
Opened 2020-10-04 10:44 UTC by jendrikw

This is the WebAssembly lexer I've been using and it worked quite well.

There is one test failure that I'm not sure how to resolve:

```
/path/pygments/.tox/lint/lib/python3.8/site-packages/pygments/lexers/webassembly.py:252: (WatLexer:arguments:pat#6) E999: Matches empty string
              (r'', Text, '#pop'),
                           ^ here
```

2020-10-04 10:47 UTC, birkenfeld commented
For the empty case, use `default('#pop')`.

2020-10-04 11:00 UTC, birkenfeld requested changes
Thanks for the PR! A few points still need addressing...

2020-10-04 11:12 UTC, jendrikw commented on pygments/lexers/webassembly.py
> +""".split()
I'm not sure what you mean by them? Should I do them like the keywords?

2020-10-04 11:21 UTC, birkenfeld commented on pygments/lexers/webassembly.py
> +""".split()
yes, please, but as a tuple (with `(...)`). This compiles the whole list into a constant without runtime overhead.

2020-10-04 11:26 UTC, jendrikw commented on pygments/lexers/webassembly.py
> +            (r'i32.const', Name.Builtin),
I can't remember why I did this, can be removed.

2020-10-04 11:38 UTC, jendrikw commented on pygments/lexers/webassembly.py
> +            (r'(.|\n)', Comment.Multiline)
I couldn't quite get this to work with nesting comments, but this does the trick:
```
        'nesting_comment': [
            (r'\(;', Comment.Multiline, '#push'),
            (r';\)', Comment.Multiline, '#pop'),
            (r'(\([^;]|;[^\)]|[^;\(])+', Comment.Multiline),
        ],
```

2020-10-04 11:39 UTC, jendrikw commented on pygments/lexers/webassembly.py
> +            (r'\t', String.Escape),
Thanks, I tend to get confused with all the escaping.

2020-10-04 13:17 UTC, jendrikw commented
I think i addressed all comments.

2020-10-04 13:43 UTC, birkenfeld commented on pygments/lexers/webassembly.py
> +            (r'(.|\n)', Comment.Multiline)
Ah right, I missed that comments nest. In that case it's
```
(r'[^;(]+', Comment.Multiline),
(r'[;(]', Comment.Multiline),
```

2020-10-06 18:26 UTC, jendrikw commented on pygments/lexers/webassembly.py
> +            (r'(.|\n)', Comment.Multiline)
Thanks, I changed it to your suggestion.

2021-02-07 07:09 UTC, Anteru commented
@birkenfeld Could you please take another look at this one?

2021-02-09 14:43 UTC, birkenfeld commented
The tests need to be fixed up (output file for the example, and snippets instead of the .py file)... Otherwise looks good, just the "versionadded" is now 2.8

2021-02-14 08:19 UTC, Anteru commented
Let's make this 2.9 as the target. Given this needs the tests updated, and 2.8 coming out today, no need to rush this in.

2021-02-17 14:57 UTC, Mesteery requested changes

2021-02-17 14:57 UTC, Mesteery commented on pygments/lexers/webassembly.py
> +    :copyright: Copyright 2006-2020 by the Pygments team, see AUTHORS.
```suggestion
    :copyright: Copyright 2006-2021 by the Pygments team, see AUTHORS.
```

2021-02-17 14:57 UTC, Mesteery commented on tests/test_webassembly.py
> +    :copyright: Copyright 2006-2020 by the Pygments team, see AUTHORS.
```suggestion
    :copyright: Copyright 2006-2021 by the Pygments team, see AUTHORS.
```

2021-02-27 16:37 UTC, Anteru commented
Can you please merge the latest master into this and update for the new test system? That seems to be causing the failures, and in theory all you need to do is to move your test file into a folder and add a golden test output file.

2021-03-24 15:08 UTC, PhilippGackstatter commented
Hi @jendrikw, I would love to have `wat` highlighting and was wondering if or when you might find the time to finish this PR? Thanks a lot!

2021-04-03 10:26 UTC, jendrikw commented
I thinks this is what you hand in mind. Could you please check if this can be merged?

2021-04-03 11:40 UTC, Anteru commented
Pretty much yes -- nearly there :) Your unit test file should also use the new mechanism, given you only test an input for a given set of tokens. Look at tests/snippets -- you can extract the input per test into a single file, and let pytest take care of the tokens. That's easier for us because we can regenerate those without having to touch Python code.

2021-04-03 12:09 UTC, jendrikw commented
That should be it.

2021-04-04 15:50 UTC, merged

2021-04-04 15:50 UTC, Anteru commented
Merged, thanks!