AMDGPU ISA Lexer
pygments/pygments pull request #1626
Opened 2020-12-10 16:09 UTC by tsymalla

This commit implements a basic lexer for the AMDGPU ISA definition.

This is based on the GPUOpen VS Code extension to be found here: https://github.com/GPUOpen-Tools/vscode_extensions/blob/master/amd-gcn-isa/syntaxes/isa.tmLanguage

I tested it with some ISA examples found on GPUOpen (https://gpuopen.com/learn/porting-detroit-2/). Please have a look at it.

2021-01-17 07:40 UTC, Anteru commented
Please add an example file -- can be a trivial shader, but there should be one to allow the automated testing to pick this lexer up.

2021-01-18 16:33 UTC, tsymalla commented
@Anteru I added a simple shader as test.

2021-01-18 16:43 UTC, Anteru requested changes

2021-01-19 18:54 UTC, tsymalla commented on AUTHORS
> +* Thomas Symalla -- AMD GCN Lexer
Renamed the lexer and any occurences.

2021-01-30 13:27 UTC, merged