Add Zenburn theme
pygments/pygments pull request #1659
Opened 2021-01-03 23:18 UTC by sirex

Zenburn theme home page: https://kippura.org/zenburnpage/

And Vim Zenburn theme repository, from which I took color codes: https://github.com/jnurmine/Zenburn

![Screenshot from 2021-01-04 01-18-15](https://user-images.githubusercontent.com/297583/103491232-a0e6b800-4e2a-11eb-9a02-4439188a6b0b.png)

2021-02-06 15:13 UTC, Anteru requested changes

2021-02-06 15:13 UTC, Anteru commented on pygments/styles/zenburn.py
> +        Keyword.Type: '#dfdfbf bold',
Can you please add line number styles here as well? There are four of those in total that should be defined.

2021-02-06 19:27 UTC, sirex commented
pygmentize -f html -O style=zenburn,full,linenos=True,hl_lines=9 test.py -o test.html

![Screenshot from 2021-02-06 21-27-52](https://user-images.githubusercontent.com/297583/107127898-0d3d5700-68c2-11eb-83fa-2fe6409bbb48.png)

2021-02-06 20:17 UTC, Anteru commented
Thanks! There are only two more colors missing, for special line numbers. You can test that with `lineospecial=2`, the color names are `line_number_special_color` and `line_number_special_background_color`. Those are used to highlight every N-th line, so you probably want something a tad brighter for them.

2021-02-06 20:18 UTC, Anteru requested changes

2021-02-06 20:18 UTC, Anteru commented on pygments/styles/zenburn.py
> +    styles = {
Please add colors for the `_special_` variant as well.

2021-02-06 22:08 UTC, sirex commented
Added `_spcial_` colors for line numbers. But something does not work with HTML generator, because just by adding `linenospecial=2` does not work. It only worked for me by also adding `noclasses=True`. It seems, that generated HTML and CSS styles does not line up.

    pygmentize -f html -O style=zenburn,full,linenos=True,linenospecial=2,noclasses=True,hl_lines=9 test.py -o /tmp/test.html


![Screenshot from 2021-02-07 00-02-22](https://user-images.githubusercontent.com/297583/107130664-8c3d8a00-68d8-11eb-985f-e97e34d196cc.png)

2021-02-07 01:44 UTC, paw-lu commented
Thanks @sirex! I was going in circles trying to figure out why the special formatting wasn't applying. Thanks for documenting your temporary solution.

2021-02-07 09:46 UTC, Anteru commented
The class issue is fixed in #1701, I think. Thanks for your contribution!

2021-02-07 09:46 UTC, merged