Add a teal lexer
pygments/pygments pull request #1671
Opened 2021-01-10 06:08 UTC by iscke

This PR adds a lexer for teal (https://developer.algorand.org/docs/reference/teal/specification/), the language used for smart contracts for the algorand blockchain.

I've tried to follow the coding standards used elsewhere in this project as closely as possible, but if anything's wrong please don't hesitate to let me know. Hope this can help.

2021-03-14 07:34 UTC, Anteru requested changes
Thanks for the contribution! Please change the tests to use the new test system using golden files, it makes it easier to maintain. (See Contributing.md for details.)

2021-03-14 07:34 UTC, Anteru commented on pygments/lexers/teal.py
> +    .. versionadded: 2.8
2.9 by now :)

2021-03-14 13:58 UTC, Anteru commented
Thanks! A few more things: You have to move _all_ examples into /examplefiles/teal (i.e. also tests/examplefiles/example.teal), and it looks like you're missing the golden test files (you can generate them using py.test --update-goldens)

2021-03-14 14:13 UTC, iscke commented
oops, thank you

2021-03-14 15:15 UTC, Anteru commented
Thanks. Just to make sure, `7777777777777777777777777777777777777777777777777774MSJUVU` is really supposed to be a single number?

2021-03-14 15:22 UTC, iscke commented
Yeah, it's a crypto account address

2021-03-14 16:17 UTC, Anteru commented
Merged, thanks!

2021-03-14 16:17 UTC, merged

2021-03-15 00:31 UTC, iscke commented
Thank you!