New lexer for Sophia contracts
pygments/pygments pull request #1974
Opened 2021-11-26 14:41 UTC by hanssv

This PR implements a Pygments lexer for Sophia, a smart contract language See: https://www.buildwithsophia.com/ and https://github.com/aeternity/aesophia

Since Sophia has its roots in Reason the lexer is derived from (though not too much remains) the reason.py lexer module.

The PR contains the lexer implementation and an example input, `test.aes`, and its expected output from pytest --update-goldens.

2021-11-27 12:24 UTC, velzevur approved these changes

2021-11-27 12:30 UTC, Anteru requested changes

2021-11-27 12:30 UTC, Anteru commented on pygments/lexers/sophia.py
> +            (r'\s+', Text),
This should be `Text.Whitespace`

2021-11-27 13:35 UTC, hanssv commented on pygments/lexers/sophia.py
> +            (r'\s+', Text),
Fixed

2021-11-28 17:48 UTC, merged

2021-11-28 17:48 UTC, Anteru commented
Merged, thanks!