Detect true-color terminal support for pygmentize
pygments/pygments pull request #2160
Opened 2022-06-12 15:40 UTC by micahcochran

For the `pygmentize` command line, this pull request adds detection of true-color support on the terminal and makes that the default formatter.  It looks up the `COLORTERM` environment variable having a value of `truecolor` or `24bit`. If that is the case, it sets the default formatter to use the `TerminalTrueColorFormatter`.

The `COLORTERM` environment variable is a convention that has been adopted by some terminals for specifying true-color is supported.

2022-06-12 20:07 UTC, Jean-Abou-Samra requested changes
Sounds good, but you need to update the documentation in `doc/docs/cmdline.rst`.

2022-06-12 23:24 UTC, micahcochran commented
I added a second commit, which documents how the terminal determines the maximum number of colors supported.

2022-06-13 05:20 UTC, Jean-Abou-Samra approved these changes

2022-06-13 05:20 UTC, Jean-Abou-Samra commented
Thanks!

2022-06-13 05:21 UTC, merged