Add Luau
pygments/pygments pull request #2605
Opened 2023-12-04 03:42 UTC by funwolf7

Adds support for Luau, a superset of Lua 5.1 created by Roblox. https://luau-lang.org/

Similar to the Lua lexer, this lexer provides options to control the builtins that it highlights. Additionally, due to Luau originating from Roblox and it still being the main usage, an option to automatically include Roblox builtins is included.

2023-12-04 22:16 UTC, funwolf7 commented on pygments/lexers/scripting.py
> +                print(index, token, value)
I distinctly remember removing this print. Not sure how it got back here.

2023-12-05 09:29 UTC, Anteru requested changes

2023-12-05 09:29 UTC, Anteru commented on pygments/lexers/scripting.py
> +            (r'[\])};]', Punctuation),
Can this be `[\])};]+` so consecutive punctuation characters don't produce separate tokens? I don't see why it can't here.

2023-12-30 16:09 UTC, Anteru requested changes

2023-12-30 16:09 UTC, Anteru commented on pygments/lexers/scripting.py
> +def _luau_make_expression(should_pop, _s):
Can you please add a comment as to what this function does and rename `_s` to something more readable?

2024-02-17 13:09 UTC, merged